Traceback (most recent call last):
  File "/home/harry/projects/ricd/testproj/manage.py", line 22, in <module>
    main()
  File "/home/harry/projects/ricd/testproj/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/core/management/commands/check.py", line 76, in handle
    self.check(
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/projects/ricd/testproj/testproj/urls.py", line 21, in <module>
    from portal import views
  File "/home/harry/projects/ricd/testproj/portal/views.py", line 30, in <module>
    from .forms import (
  File "/home/harry/projects/ricd/testproj/portal/forms/__init__.py", line 5, in <module>
    from .funding import *
  File "/home/harry/projects/ricd/testproj/portal/forms/funding.py", line 57, in <module>
    class ForwardRemoteProgramFundingAgreementForm(forms.ModelForm):
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/forms/models.py", line 300, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/forms/models.py", line 225, in fields_for_model
    formfield = f.formfield(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/db/models/fields/related.py", line 1227, in formfield
    return super().formfield(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harry/projects/ricd/venv/lib/python3.11/site-packages/django/db/models/fields/related.py", line 1144, in formfield
    raise ValueError(
ValueError: Cannot create form field for 'council' yet, because its related model 'core.Council' has not been loaded yet
